# Generated by Django 4.0.4 on 2023-10-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0009_student_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='university',
        ),
    ]
