# Generated by Django 4.0.4 on 2023-11-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0013_university_courses_prerequst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_ID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
