# Generated by Django 4.0.4 on 2023-11-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0014_alter_student_gpa_alter_student_university_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartadvisor.level'),
        ),
    ]
