# Generated by Django 4.0.4 on 2023-11-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0023_remove_recommended_course_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='semester_name',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='semester_name',
        ),
    ]
