# Generated by Django 4.0.4 on 2023-11-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0024_remove_level_semester_name_delete_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='semester_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='semester_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartadvisor.semester_name'),
        ),
    ]
