# Generated by Django 4.0.4 on 2023-10-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preRequst',
            field=models.ManyToManyField(blank=True, null=True, to='smartadvisor.course'),
        ),
    ]
