# Generated by Django 4.0.4 on 2023-10-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0002_alter_course_prerequst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preRequst',
            field=models.ManyToManyField(blank=True, to='smartadvisor.course'),
        ),
    ]
