# Generated by Django 4.0.4 on 2023-10-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0003_alter_course_prerequst'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours_condition',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Hours_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='university_courses',
            name='hours_condition',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
