# Generated by Django 4.0.4 on 2023-10-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0004_course_hours_condition_student_hours_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='semester_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
