# Generated by Django 4.0.4 on 2023-10-25 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0005_semester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='semester_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartadvisor.semester_name'),
        ),
    ]
