# Generated by Django 4.0.4 on 2023-10-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0007_department_completly_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='completly_hours',
        ),
    ]
