# Generated by Django 4.0.4 on 2023-10-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0012_college_number_of_required_optional_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_courses',
            name='preRequst',
            field=models.ManyToManyField(blank=True, to='smartadvisor.university_courses'),
        ),
    ]
