# Generated by Django 4.0.4 on 2023-11-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0016_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='major',
        ),
        migrations.AddField(
            model_name='course',
            name='majors',
            field=models.ManyToManyField(to='smartadvisor.major'),
        ),
    ]
