# Generated by Django 4.0.4 on 2023-11-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0018_level2_sublevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartadvisor.level2'),
        ),
        migrations.AddField(
            model_name='sublevel',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartadvisor.level2'),
        ),
    ]
