# Generated by Django 4.0.4 on 2023-11-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0025_semester_name_level_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_ID',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university_courses',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
