# Generated by Django 4.0.4 on 2023-12-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0027_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='majors',
            field=models.ManyToManyField(null=True, to='smartadvisor.major'),
        ),
    ]
