# Generated by Django 4.0.4 on 2023-12-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0028_alter_course_majors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='majors',
            field=models.ManyToManyField(blank=True, to='smartadvisor.major'),
        ),
    ]
