# Generated by Django 4.0.4 on 2023-12-08 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0029_alter_course_majors'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='number_of_levels',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LevelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_required_optional_courses', models.IntegerField(default=2)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartadvisor.college')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartadvisor.level')),
            ],
        ),
    ]
